# Generated by Django 4.0.6 on 2023-02-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0002_docente_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='cursos',
            field=models.ManyToManyField(null=True, to='docentes.curso'),
        ),
    ]
