# Generated by Django 4.0.6 on 2023-02-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0004_alter_docente_cursos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='cursos',
            field=models.ManyToManyField(blank=True, to='docentes.curso'),
        ),
    ]
