# Generated by Django 4.0.6 on 2023-02-14 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experimentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='decricao',
            field=models.CharField(default='', max_length=255, verbose_name='Descrição Curta'),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='experimento',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='experimentos.experimento'),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='nome',
            field=models.FileField(max_length=255, unique=True, upload_to='uploads/', verbose_name='Arquivo'),
        ),
    ]
