# Generated by Django 4.0.6 on 2023-02-14 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experimentos', '0002_arquivo_decricao_arquivo_experimento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arquivo',
            name='experimento',
        ),
    ]
