# Generated by Django 4.0.6 on 2023-02-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimentos', '0003_remove_arquivo_experimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='decricao',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Descrição Curta'),
        ),
    ]
