# Generated by Django 4.0.6 on 2023-02-14 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experimentos', '0004_alter_arquivo_decricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='experimento',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='experimentos.experimento'),
        ),
    ]
