# Generated by Django 4.0.6 on 2023-02-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimentos', '0005_arquivo_experimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimento',
            name='descricao',
            field=models.TextField(blank=True),
        ),
    ]
